### ISSUE TITLE
Typescript definition of navigate function doesn't have NavigateOptions as optional

### ISSUE THREAD

**Issue by zsigix** [medium-tech/van-cone#2]
Version: 0.0.7
 
Action: An internal Typescript class needs to navigate programmatically over to a routed page, so the `navigate` function is called. The page doesn't have any special parameters or query strings, so a `NavigateOptions` object is not specified.
Expected: Per the documentation, the `options` parameter is optional when calling `navigate`.
Actual: The `options` parameter is not optional, per the `spa.d.ts` definition file.
 
As of now, I can use `@ts-ignore` to bypass this and compile normally, but I figured this should be addressed.
 
Thanks!

**Comment by b-rad-c** [comment]
Thanks for catching this @zsigix, I've created a new release 0.0.8 which fixes this. Additionally I noticed the `pushHistory` function had the same problem.
