### ISSUE TITLE
TypeError: Right side of assignment cannot be destructured

### ISSUE THREAD

**Issue by strash** [medium-tech/van-cone#4]
After #2 if `NavigateOptions` is omitted it causes a TypeError:
`TypeError: Right side of assignment cannot be destructured`.

https://github.com/medium-tech/van-cone/blob/048e3fb8239e17521b450678919cb3d298e5b0a1/src/spa.js#L161
The `options` argument here is `undefined` in that case.

**Comment by b-rad-c** [comment]
Thanks for reporting. Will have a fix out soon.

**Comment by b-rad-c** [comment]
thanks for reporting, fix coming soon!

**Comment by b-rad-c** [comment]
This is fixed in release 1.0.0, thanks for your report!
